const explanation = [
   
      {"Number":"1", "Sequence":"7,7,7,7,7,7", "Title":"Čichen / Tvoření", "Text":"Dokonalé nebe, stálost."},
      {"Number":"2", "Sequence":"8,8,8,8,8,8", "Title":"Kchun / Příjmání", "Text":"Dokonalé nebe, stálost."},
      {"Number":"3", "Sequence":"8,7,8,8,8,7", "Title":"Čun / Obtížě začátků", "Text":"Dokonalé nebe, stálost."},
      {"Number":"4", "Sequence":"7,8,8,8,7,8", "Title":"Meng / Pošetilost mládí", "Text":"Dokonalé nebe, stálost."},
      {"Number":"5", "Sequence":"8,7,8,7,8,8", "Title":"Sü / Čekání (Výživa)", "Text":"Dokonalé nebe, stálost."},
      {"Number":"6", "Sequence":"8,8,8,7,8,7", "Title":"Sung / Svár", "Text":"Dokonalé nebe, stálost."},
      {"Number":"7", "Sequence":"8,8,8,8,7,8", "Title":"Š' / Vojsko", "Text":"Dokonalé nebe, stálost."},
      {"Number":"8", "Sequence":"8,7,8,8,8,8", "Title":"Pi / Soudržnost", "Text":"Dokonalé nebe, stálost."},
      {"Number":"9", "Sequence":"7,7,8,7,7,7", "Title":"Siao-čchu / Krocení malým", "Text":"Dokonalé nebe, stálost."},
      {"Number":"10", "Sequence":"7,7,7,8,7,7", "Title":"Lü / Vykročení", "Text":"Dokonalé nebe, stálost."},
      {"Number":"11", "Sequence":"8,8,8,7,7,7", "Title":"Tchaj / Mír", "Text":"Dokonalé nebe, stálost."},
      {"Number":"12", "Sequence":"7,7,7,8,8,8", "Title":"Pchi / Uváznutí", "Text":"Dokonalé nebe, stálost."},
      {"Number":"13", "Sequence":"7,7,7,7,8,7", "Title":"Tchung-žen / Společenství s lidmi", "Text":"Dokonalé nebe, stálost."},
      {"Number":"14", "Sequence":"7,8,7,7,7,7", "Title":"Ta-jou / Vlastnictví velkého", "Text":"Dokonalé nebe, stálost."},
      {"Number":"15", "Sequence":"8,8,8,7,8,8", "Title":"Ťien / Skromnost", "Text":"Dokonalé nebe, stálost."},
      {"Number":"16", "Sequence":"8,8,7,8,8,8", "Title":"Jü / Nadšení", "Text":"Dokonalé nebe, stálost."},
      {"Number":"17", "Sequence":"8,7,7,8,8,7", "Title":"Suej / Následování", "Text":"Dokonalé nebe, stálost."},
      {"Number":"18", "Sequence":"7,8,8,7,7,8", "Title":"Ku / Práce na pokaženém", "Text":"Dokonalé nebe, stálost."},
      {"Number":"19", "Sequence":"8,8,8,8,7,7", "Title":"Lin / Sblížení", "Text":"Dokonalé nebe, stálost."},
      {"Number":"20", "Sequence":"7,7,8,8,8,8", "Title":"Kuan / Pozorování", "Text":"Dokonalé nebe, stálost."},
      {"Number":"21", "Sequence":"7,8,7,8,8,7", "Title":"Š'-chuo / Překousnutí", "Text":"Dokonalé nebe, stálost."},
      {"Number":"22", "Sequence":"7,8,8,7,8,7", "Title":"Pi / Půvab", "Text":"Dokonalé nebe, stálost."},
      {"Number":"23", "Sequence":"7,8,8,8,8,8", "Title":"Po / Rozpad", "Text":"Dokonalé nebe, stálost."},
      {"Number":"24", "Sequence":"8,8,8,8,8,7", "Title":"Fu / Návrat (Doba obratu)", "Text":"Dokonalé nebe, stálost."},
      {"Number":"25", "Sequence":"7,7,7,8,8,7", "Title":"Wu-wang / Nevinnost (Nečekané)", "Text":"Dokonalé nebe, stálost."},
      {"Number":"26", "Sequence":"7,8,8,7,7,7", "Title":"Ta-čchu / Krocení velkým", "Text":"Dokonalé nebe, stálost."},
      {"Number":"27", "Sequence":"7,8,8,8,8,7", "Title":"I / Koutky úst (Výživa)", "Text":"Dokonalé nebe, stálost."},
      {"Number":"28", "Sequence":"8,7,7,7,7,8", "Title":"Ta-kuo / Převaha velkého", "Text":"Dokonalé nebe, stálost."},
      {"Number":"29", "Sequence":"8,7,8,8,7,8", "Title":"Kchan / Hlubina, voda", "Text":"Dokonalé nebe, stálost."},
      {"Number":"30", "Sequence":"7,8,7,7,8,7", "Title":"Li / Lpění, oheň", "Text":"Dokonalé nebe, stálost."},
      {"Number":"31", "Sequence":"8,7,7,7,8,8", "Title":"Sien / Působení (Namlouvání)", "Text":"Dokonalé nebe, stálost."},
      {"Number":"32", "Sequence":"7,7,8,8,8,7", "Title":"Cheng / Trvání", "Text":"Dokonalé nebe, stálost."},
      {"Number":"33", "Sequence":"7,7,7,7,8,8", "Title":"Tun / Ústup", "Text":"Dokonalé nebe, stálost."},
      {"Number":"34", "Sequence":"8,8,7,7,7,7", "Title":"Ta-čuang / Moc velkého", "Text":"Dokonalé nebe, stálost."},
      {"Number":"35", "Sequence":"7,8,7,8,8,8", "Title":"Ťin / Pokrok", "Text":"Dokonalé nebe, stálost."},
      {"Number":"36", "Sequence":"8,8,8,7,8,7", "Title":"Ming-i / Zatemění", "Text":"Dokonalé nebe, stálost."},
      {"Number":"37", "Sequence":"7,7,8,7,8,7", "Title":"Ťia-žen / Rod", "Text":"Dokonalé nebe, stálost."},
      {"Number":"38", "Sequence":"7,8,7,8,7,7", "Title":"Kchuej / Protiklad", "Text":"Dokonalé nebe, stálost."},
      {"Number":"39", "Sequence":"8,7,8,7,8,8", "Title":"Ťien / Překážka", "Text":"Dokonalé nebe, stálost."},
      {"Number":"40", "Sequence":"8,8,7,8,7,8", "Title":"Ťie / Osvobození", "Text":"Dokonalé nebe, stálost."},
      {"Number":"41", "Sequence":"7,8,8,8,7,7", "Title":"Sun / Ubývání", "Text":"Dokonalé nebe, stálost."},
      {"Number":"42", "Sequence":"7,7,8,8,8,7", "Title":"I / Přibývání", "Text":"Dokonalé nebe, stálost."},
      {"Number":"43", "Sequence":"8,7,7,7,7,7", "Title":"Kuej / Průlom (Rozhodnost)", "Text":"Dokonalé nebe, stálost."},
      {"Number":"44", "Sequence":"7,7,7,7,7,8", "Title":"Kou / Vykročení vstříc", "Text":"Dokonalé nebe, stálost."},
      {"Number":"45", "Sequence":"8,7,7,8,8,8", "Title":"Cuej / Shromáždění", "Text":"Dokonalé nebe, stálost."},
      {"Number":"46", "Sequence":"8,8,8,7,7,8", "Title":"Šeng / Pronikání vzhůru", "Text":"Dokonalé nebe, stálost."},
      {"Number":"47", "Sequence":"8,7,7,8,7,8", "Title":"Kchun / Tíseň", "Text":"Dokonalé nebe, stálost."},
      {"Number":"48", "Sequence":"8,7,8,7,7,8", "Title":"Ťing / Studna", "Text":"Dokonalé nebe, stálost."},
      {"Number":"49", "Sequence":"8,7,7,7,8,7", "Title":"Ke / Převrat (Pelichání)", "Text":"Dokonalé nebe, stálost."},
      {"Number":"50", "Sequence":"7,8,7,7,7,8", "Title":"Ťing / Kotel", "Text":"Dokonalé nebe, stálost."},
      {"Number":"51", "Sequence":"8,8,7,8,8,7", "Title":"Čen / Podnět (Otřes, hrom)", "Text":"Dokonalé nebe, stálost."},
      {"Number":"52", "Sequence":"7,8,8,7,8,8", "Title":"Ken / Stání, hora", "Text":"Dokonalé nebe, stálost."},
      {"Number":"53", "Sequence":"7,7,8,7,8,8", "Title":"Ťien / Vývoj (Pozvolný pokrok)", "Text":"Dokonalé nebe, stálost."},
      {"Number":"54", "Sequence":"8,8,7,8,7,7", "Title":"Kuj-mej / Dívka k provdání", "Text":"Dokonalé nebe, stálost."},
      {"Number":"55", "Sequence":"8,8,7,7,8,7", "Title":"Feng / Hojnost", "Text":"Dokonalé nebe, stálost."},
      {"Number":"56", "Sequence":"7,8,7,7,8,8", "Title":"Lü / Poutník", "Text":"Dokonalé nebe, stálost."},
      {"Number":"57", "Sequence":"7,7,8,7,7,8", "Title":"Sun / Mírnost (Pronikavost, Vítr)", "Text":"Dokonalé nebe, stálost."},
      {"Number":"58", "Sequence":"8,7,7,8,7,7", "Title":"Tuej / Radost, Jezero", "Text":"Dokonalé nebe, stálost."},
      {"Number":"59", "Sequence":"7,7,8,8,7,8", "Title":"Chuan / Rozptýlení", "Text":"Dokonalé nebe, stálost."},
      {"Number":"60", "Sequence":"8,7,8,8,7,7", "Title":"Ťie / Omezení", "Text":"Dokonalé nebe, stálost."},
      {"Number":"61", "Sequence":"7,7,8,8,7,7", "Title":"Čung-fou / Vnitřní pravda", "Text":"Dokonalé nebe, stálost."},
      {"Number":"62", "Sequence":"8,8,7,7,8,8", "Title":"Siao-kuo / Převaha malého", "Text":"Dokonalé nebe, stálost."},
      {"Number":"63", "Sequence":"8,7,8,7,8,7", "Title":"Čchi-ti / Po dokončení", "Text":"Dokonalé nebe, stálost."},
      {"Number":"64", "Sequence":"7,8,7,8,7,8", "Title":"Wej-ti / Před dokončením", "Text":"Dokonalé nebe, stálost."}
    
    ]